// Generated by CoffeeScript 1.3.3
var app, express, http, io, routes, routes2, routes3, server, sio;

express = require('express');

http = require('http');

app = express();

server = http.createServer(app);

sio = require('socket.io').listen(server);

app.configure(function() {
  app.set('views', __dirname + '/views');
  app.set('view engine', 'jade');
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(require('stylus').middleware({
    src: __dirname + '/public'
  }));
  app.use(app.router);
  return app.use(express.static(__dirname + '/public'));
});

app.configure('development', function() {
  return app.use(express.errorHandler({
    dumpExceptions: true,
    showStack: true
  }));
});

app.configure('production', function() {
  return app.use(express.errorHandler());
});

server.listen(process.env.PORT || 3000);

routes = require('./routes');

app.get('/', routes.index);

routes2 = require('./routes/enter');

app.post('/enter', routes2.enter);

io = sio;

routes3 = require('./routes/chat');

routes3.io = io;

io.sockets.on('connection', routes3.chat);
