// Generated by CoffeeScript 1.3.3

exports.enter = function(req, res) {
  var result;
  result = {
    title: 'Chat Translator',
    username: req.body.username
  };
  return res.render('room', result);
};
